export interface AdsFilterState {
  category: string;
  query: string;
  subCategory: string;
  minPrice: number | '';
  maxPrice: number | '';
  location: string;
  // Car Specs
  carPurpose: string;
  selectedBrand: string;
  selectedModel: string;
  minYear: string;
  maxYear: string;
  minMileage: number | '';
  maxMileage: number | '';
  transmission: string;
  fuelType: string;
  carBodyType: string;
  carCondition: string;
  enginePower: string;
  engineSize: string;
  carDrive: string;
  carColor: string;
  carWarranty: string;
  carAdvertiser: string;
  adDateRange: string;
  // Real Estate Specs
  rePurpose: string;
  propType: string;
  isHotelApt: boolean;
  aptFurnished: string;
  minRentPeriod: string;
  bedsCount: string;
  hotelAmenities: string[];
  minNetArea: number | '';
  maxNetArea: number | '';
  rooms: string;
  bathrooms: string;
  aptFloor: string;
  buildingTotalFloors: string;
  buildingAge: string;
  heatingType: string;
  kitchenType: string;
  balconyCount: string;
  hasElevator: string;
  hasParking: string;
  houseStatus: string;
  inComplex: string;
  titleDeedType: string;
  propertyDirection: string;
  advertiserType: string;
  onlyWithVideo: boolean;
  villaFloors: string;
  villaAmenities: string[];
  landZoning: string;
  landFrontage: string;
  officeFitted: string;
  shopHasLicense: string;
  minArea: number | '';
  maxArea: number | '';
  deliveryYear?: string;
  projectStatus?: string;
  paymentPlan?: string;
  projectFloors?: number | '';
  projectType?: string;
  projectFinishing?: string;
  projectLandArea?: number | '';
  projectUnitsCount?: number | '';
  projectFacilities?: string[];
  projectAmenities?: string[];
  sortBy: string;
}
